/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MultiQueryService } from "./MultiQueryService";
export type { State } from "./State";
export * as factories from "./factories";
export { MultiQueryService__factory } from "./factories/MultiQueryService__factory";
export { State__factory } from "./factories/State__factory";
